// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.conevento.Entities
{
    public partial class CatTiposUidad
    {
        public CatTiposUidad()
        {
            CatProductosServicios = new HashSet<CatProductosServicio>();
        }

        public int Int { get; set; }
        public string TipoUnidad { get; set; }
        public bool? Activo { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<CatProductosServicio> CatProductosServicios { get; set; }
    }
}