// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.conevento.Entities
{
    public partial class Evento
    {
        public Evento()
        {
            ListaProductosEventos = new HashSet<ListaProductosEvento>();
        }

        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombreEvento { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? FormaPago { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int? IdUsuario { get; set; }
        public int? IdCatEstado { get; set; }
        public int? IdCatMunicipio { get; set; }
        public int? GenteEsperada { get; set; }
        public string CalleNumero { get; set; }
        public string NumInt { get; set; }
        public string NumExt { get; set; }
        public string Cp { get; set; }
        public string Colonia { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string DetallesEvento { get; set; }
        public DateTime? FechaPago { get; set; }
        public string ReferenciaPago { get; set; }
        public bool? Pagado { get; set; }
        public string ClaveSeguimientoCarrito { get; set; }

        public virtual CatMunicipio IdCatMunicipioNavigation { get; set; }
        public virtual User IdUsuarioNavigation { get; set; }
        public virtual ICollection<ListaProductosEvento> ListaProductosEventos { get; set; }
    }
}